version: '3.8'

services:
  postgres:
    container_name: dev_database
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - authJs_prisma_template:/var/lib/postgresql/data

volumes:
  authJs_prisma_template: 